name: 'Build and Push Docker Image'
description: 'Build and push a Docker image to GHCR'

inputs:
  image-dir:
    description: 'Directory containing the Dockerfile'
    required: true
  registry:
    description: 'Container registry'
    required: true
    default: 'ghcr.io'
  repository-owner:
    description: 'Repository owner'
    required: true
  repository-name:
    description: 'Repository name'
    required: true
  publish-release-tag:
    description: 'Whether to publish release tag (without date)'
    required: true
    default: 'true'
  use-cache:
    description: 'Whether to use build cache for faster builds'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Load configuration
      id: config
      run: |
        # Load values from config.yml
        echo "registry=$(bash scripts/config-loader.sh get registry.url)" >> $GITHUB_OUTPUT
        echo "owner=$(bash scripts/config-loader.sh get registry.owner)" >> $GITHUB_OUTPUT
        echo "repository=$(bash scripts/config-loader.sh get registry.repository)" >> $GITHUB_OUTPUT
        echo "base_ubuntu=$(bash scripts/config-loader.sh base-ubuntu)" >> $GITHUB_OUTPUT
        echo "base_runner=$(bash scripts/config-loader.sh base-runner)" >> $GITHUB_OUTPUT
        echo "buildx_version=$(bash scripts/config-loader.sh get actions.setup-buildx)" >> $GITHUB_OUTPUT
        echo "login_version=$(bash scripts/config-loader.sh get actions.login-action)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@${{ steps.config.outputs.buildx_version }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@${{ steps.config.outputs.login_version }}
      with:
        registry: ${{ steps.config.outputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and push image
      run: |
        DATE="${{ steps.date.outputs.date }}"
        RELEASE_TAG="${{ inputs.publish-release-tag }}"
        USE_CACHE="${{ inputs.use-cache }}"
        IMAGE_DIR="${{ inputs.image-dir }}"
        FOLDER_NAME=$(basename "$IMAGE_DIR")
        CACHE_KEY="docker-$FOLDER_NAME-${{ hashFiles(format('{0}/**', inputs.image-dir)) }}"
        
        # Use config for registry path
        REGISTRY="${{ steps.config.outputs.registry }}"
        OWNER="${{ steps.config.outputs.owner }}"
        REPO="${{ steps.config.outputs.repository }}"

        echo "=== Building $FOLDER_NAME from $IMAGE_DIR ==="

        # Set up cache options
        CACHE_OPTIONS=""
        if [ "$USE_CACHE" = "true" ]; then
          echo "Setting up Docker build cache..."
          CACHE_OPTIONS="--cache-from type=gha,scope=$CACHE_KEY --cache-to type=gha,mode=max,scope=$CACHE_KEY"
        fi

        # Pass base images as build args
        BUILD_ARGS="--build-arg BASE_IMAGE=${{ steps.config.outputs.base_runner }}"
        if [ "$FOLDER_NAME" = "base" ]; then
          BUILD_ARGS="--build-arg BASE_IMAGE=${{ steps.config.outputs.base_ubuntu }}"
        fi

        # Build and push with date tag
        docker buildx build \
          --platform linux/amd64 \
          --tag "$REGISTRY/$OWNER/$REPO:$FOLDER_NAME-$DATE" \
          $BUILD_ARGS \
          $CACHE_OPTIONS \
          --push \
          "$IMAGE_DIR"

        # Also push release tag (without date) if requested
        if [ "$RELEASE_TAG" = "true" ]; then
          docker buildx build \
            --platform linux/amd64 \
            --tag "$REGISTRY/$OWNER/$REPO:$FOLDER_NAME" \
            $BUILD_ARGS \
            $CACHE_OPTIONS \
            --push \
            "$IMAGE_DIR"
        fi

        echo "✅ Published: $REGISTRY/$OWNER/$REPO:$FOLDER_NAME-$DATE"
        if [ "$RELEASE_TAG" = "true" ]; then
          echo "✅ Published: $REGISTRY/$OWNER/$REPO:$FOLDER_NAME"
        fi
      shell: bash