name: 'Build and Push Docker Image'
description: 'Build and push a Docker image to GHCR'

inputs:
  image-dir:
    description: 'Directory containing the Dockerfile'
    required: true
  registry:
    description: 'Container registry'
    required: true
    default: 'ghcr.io'
  repository-owner:
    description: 'Repository owner'
    required: true
  repository-name:
    description: 'Repository name'
    required: true
  publish-release-tag:
    description: 'Whether to publish release tag (without date)'
    required: true
    default: 'true'
  use-cache:
    description: 'Whether to use build cache for faster builds'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and push image
      run: |
        DATE="${{ steps.date.outputs.date }}"
        RELEASE_TAG="${{ inputs.publish-release-tag }}"
        USE_CACHE="${{ inputs.use-cache }}"
        IMAGE_DIR="${{ inputs.image-dir }}"
        FOLDER_NAME=$(basename "$IMAGE_DIR")
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA="${SHORT_SHA:0:8}"
        CACHE_KEY="docker-$FOLDER_NAME-${{ hashFiles(format('{0}/**', inputs.image-dir)) }}"

        echo "=== Building $FOLDER_NAME from $IMAGE_DIR ==="

        # Set up cache options
        CACHE_OPTIONS=""
        if [ "$USE_CACHE" = "true" ]; then
          echo "Setting up Docker build cache..."
          CACHE_OPTIONS="--cache-from type=gha,scope=$CACHE_KEY --cache-to type=gha,mode=max,scope=$CACHE_KEY"
        fi

        # Build and push with date tag (multi-platform)
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag "${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.repository-name }}:$FOLDER_NAME-$DATE" \
          $CACHE_OPTIONS \
          --push \
          "$IMAGE_DIR"

        # Also push release tag (without date) if requested
        if [ "$RELEASE_TAG" = "true" ]; then
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.repository-name }}:$FOLDER_NAME" \
            $CACHE_OPTIONS \
            --push \
            "$IMAGE_DIR"
        fi

        echo "✅ Published: ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.repository-name }}:$FOLDER_NAME-$DATE"
        if [ "$RELEASE_TAG" = "true" ]; then
          echo "✅ Published: ${{ inputs.registry }}/${{ inputs.repository-owner }}/${{ inputs.repository-name }}:$FOLDER_NAME"
        fi
      shell: bash